# Generated by Django 3.0.6 on 2020-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
